name: Build and deploy Album API application to Azure Container Registry

on:
  workflow_dispatch:

env:
  AZURE_ACR_NAME: acrauaecontainerapps
  REGISTRY_NAMESPACE_NAME: albumapi 
  CONTAINERAPP_NAME: albumapicsharp

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Docker Login'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.AZURE_ACR_NAME }}.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: 'Compose Customized Docker Image'
        shell: bash
        run: |
          # If your function app project is not located in your repository's root
          # Please change the path to your directory for docker build
          cd src
          docker build . -t ${{ env.AZURE_ACR_NAME }}/${{ env.REGISTRY_NAMESPACE_NAME }}/${{ env.CONTAINERAPP_NAME }}:latest
          docker push ${{ env.AZURE_ACR_NAME }}/${{ env.REGISTRY_NAMESPACE_NAME }}/${{ env.CONTAINERAPP_NAME }}:latest

      - name: Azure logout
        run: |
          az logout